lib/task_tracker_web/router.ex
defmodule TaskTrackerWeb.Router do
  use TaskTrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TaskTrackerWeb.Plugs.FetchSession
  end

  pipeline :ajax do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug TaskTrackerWeb.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TaskTrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/tasks", TaskController
    resources "/users", UserController
    resources "/profile", UserController
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
  end

  scope "/ajax", TaskTrackerWeb do
    pipe_through :ajax
    resources "/time_blocks", TimeBlockController, except: [:new, :edit]
  end

  # Other scopes may use custom stacks.
  # scope "/api", TaskTrackerWeb do
  #   pipe_through :api
  # end
end

lib/task_tracker/users/user.ex
defmodule TaskTracker.Users.User do
  use Ecto.Schema
  import Ecto.Changeset


  schema "users" do
    field :name, :string
    field :admin, :boolean, default: false
    belongs_to :manager, TaskTracker.Users.User
    has_many :users, TaskTracker.Users.User, foreign_key: :manager_id
    has_many :tasks, TaskTracker.Tasks.Task

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :admin, :manager_id])
    |> validate_required([:name, :admin])
  end
end

lib/task_tracker/users/users.ex
defmodule TaskTracker.Users do
  @moduledoc """
  The Users context.
  """

  import Ecto.Query, warn: false
  alias TaskTracker.Repo

  alias TaskTracker.Users.User

  @doc """
  Returns the list of users.

  ## Examples

      iex> list_users()
      [%User{}, ...]

  """
  def list_users do
    Repo.all(User)
  end

  def list_manager_underlings(manager_id) do
    query = from u in User,
             where: u.manager_id == ^manager_id,
             select: u
    Repo.all(query)
  end

  @doc """
  Gets a single user.

  Raises `Ecto.NoResultsError` if the User does not exist.

  ## Examples

      iex> get_user!(123)
      %User{}

      iex> get_user!(456)
      ** (Ecto.NoResultsError)

  """
  def get_user!(id), do: Repo.get!(User, id)

  def get_user(id) do
    Repo.one from u in User,
      where: u.id == ^id,
      preload: [:manager]
  end


  def get_user_by_name(name) do
    Repo.get_by(User, name: name)
  end

  def id_to_name(id) do
    if id == nil do
      "nil"
    else
      user = get_user!(id)
      user.name
    end
  end

  def name_to_id(name) do
    user = get_user_by_name(name)
    user.id
  end

  def user_id_to_manager_name(manager_id) do
    if manager_id == nil do
      "No Manager Assigned"
    else
      manager = TaskTracker.Users.get_user!(manager_id)
      manager.name
    end
  end

  @doc """
  Creates a user.

  ## Examples

      iex> create_user(%{field: value})
      {:ok, %User{}}

      iex> create_user(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_user(attrs \\ %{}) do
    %User{}
    |> User.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a user.

  ## Examples

      iex> update_user(user, %{field: new_value})
      {:ok, %User{}}

      iex> update_user(user, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_user(%User{} = user, attrs) do
    user
    |> User.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a User.

  ## Examples

      iex> delete_user(user)
      {:ok, %User{}}

      iex> delete_user(user)
      {:error, %Ecto.Changeset{}}

  """
  def delete_user(%User{} = user) do
    Repo.delete(user)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking user changes.

  ## Examples

      iex> change_user(user)
      %Ecto.Changeset{source: %User{}}

  """
  def change_user(%User{} = user) do
    User.changeset(user, %{})
  end
end

lib/task_tracker_web/controllers/user_controller.ex
defmodule TaskTrackerWeb.UserController do
  use TaskTrackerWeb, :controller

  alias TaskTracker.Users
  alias TaskTracker.Users.User
  alias TaskTracker.Repo

  def index(conn, _params) do
    if conn.request_path == "/profile" && conn.assigns.current_user do
      user_id = conn.assigns.current_user.id
      profile(conn, %{"id" => user_id})
    else
      users = Users.list_users()
      |> Repo.preload(:manager)
      render(conn, "index.html", users: users)
    end
  end

  def new(conn, _params) do
    changeset = Users.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Users.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> put_session(:user_id, user.id)
        |> redirect(to: Routes.user_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Users.get_user!(id)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Users.get_user!(id)
    changeset = Users.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Users.get_user!(id)

    case Users.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Users.get_user!(id)
    {:ok, _user} = Users.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: Routes.user_path(conn, :index))
  end

  def profile(conn, %{"id" => id}) do
    user = Users.get_user!(id)
    user_tasks = TaskTracker.Tasks.list_user_tasks(id)
    manager_underlings = TaskTracker.Users.list_manager_underlings(id)
    render(conn, "profile.html", user: user, user_tasks: user_tasks,
      manager_underlings: manager_underlings)
  end
end

lib/task_tracker_web/views/user_view.ex
defmodule TaskTrackerWeb.UserView do
  use TaskTrackerWeb, :view
end

lib/task_tracker_web/templates/user/index.html.eex
<h1>Listing Users</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Manager</th>
      <th>Admin</th>
      <th>Date Created</th>

      <th></th>
    </tr>
  </thead>
  <tbody>

<%= for user <- @users do %>
    <tr>
      <td><%= user.name %></td>
      <!-- TODO: Get manager name to show up here  -->
      <td><%=  TaskTracker.Users.user_id_to_manager_name(user.manager_id) %></td>
      <td><%= user.admin %></td>
      <td><%= user.inserted_at %>

      <td><%= link "Show", to: Routes.user_path(@conn, :show, user), class: "btn btn-info"  %></td>
      <td><%= link "Edit", to: Routes.user_path(@conn, :edit, user), class: "btn btn-light" %></td>
      <td><%= link "Delete", to: Routes.user_path(@conn, :delete, user), class: "btn btn-secondary", method: :delete, data: [confirm: "Are you sure?"] %></td>

    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: Routes.user_path(@conn, :new), class: "btn btn-primary" %></span>

lib/task_tracker_web/templates/user/profile.html.eex
<h1><%= @user.name %>'s Profile</h1>

<ul class="list-group">
  <li class="list-group-item">
    <strong>name:</strong>
    <%= @user.name %>
  </li>

  <li class="list-group-item">
    <strong>Admin:</strong>
    <%= @user.admin %>
  </li>

  <li class="list-group-item">
    <strong>Date Created:</strong>
    <%= @user.inserted_at %>
  </li>

</ul>
</br>
<h2><%= @user.name %>'s Tasks</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Complete</th>
      <th>User</th>
      <th>Date Created</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for task <- @user_tasks do %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.complete %></td>
        <td><%= TaskTracker.Tasks.user_id_to_name(task.user_id) %></td>
        <td><%= task.inserted_at %></td>

        <td><%= link "Show", to: Routes.task_path(@conn, :show, task), class: "btn btn-info"  %></td>
        <td><%= link "Edit", to: Routes.task_path(@conn, :edit, task), class: "btn btn-light" %></td>
        <td><%= link "Delete", to: Routes.task_path(@conn, :delete, task), class: "btn btn-secondary", method: :delete, data: [confirm: "Are you sure?"] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= if @manager_underlings do %>
  <h2><%= @user.name %>'s Employees</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>

        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= for underling <- @manager_underlings do %>
        <tr>
          <td><%= underling.name %></td>
          <!-- TODO: Add more to this table when you can think of it -->

          <td><%= link "Show", to: Routes.user_path(@conn, :show, underling), class: "btn btn-info"  %></td>
          <td><%= link "Edit", to: Routes.user_path(@conn, :edit, underling), class: "btn btn-light" %></td>
          <td><%= link "Delete", to: Routes.user_path(@conn, :delete, underling), class: "btn btn-secondary", method: :delete, data: [confirm: "Are you sure?"] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<span><%= link "Edit", to: Routes.user_path(@conn, :edit, @user), class: "btn btn-primary" %></span>
<span><%= link "Back", to: Routes.user_path(@conn, :index), class: "btn btn-secondary" %></span>

lib/task_tracker_web/templates/user/show.html.eex
<h1>User Information</h1>

<ul class="list-group">
  <li class="list-group-item">
    <strong>name:</strong>
    <%= @user.name %>
  </li>

  <li class="list-group-item">
    <strong>Admin:</strong>
    <%= @user.admin %>
  </li>

  <li class="list-group-item">
    <strong>Date Created:</strong>
    <%= @user.inserted_at %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.user_path(@conn, :edit, @user), class: "btn btn-primary" %></span>
<span><%= link "Back", to: Routes.user_path(@conn, :index), class: "btn btn-secondary" %></span>