lib/task_tracker_web/router.ex
defmodule TaskTrackerWeb.Router do
  use TaskTrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TaskTrackerWeb.Plugs.FetchSession
  end

  pipeline :ajax do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug TaskTrackerWeb.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TaskTrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/tasks", TaskController
    resources "/users", UserController
    resources "/profile", UserController
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
  end

  scope "/ajax", TaskTrackerWeb do
    pipe_through :ajax
    resources "/time_blocks", TimeBlockController, except: [:new, :edit]
  end

  # Other scopes may use custom stacks.
  # scope "/api", TaskTrackerWeb do
  #   pipe_through :api
  # end
end

lib/task_tracker/tasks/task.ex
defmodule TaskTracker.Tasks.Task do
  use Ecto.Schema
  import Ecto.Changeset

  alias Decimal


  schema "tasks" do
    field :complete, :boolean, default: false
    field :desc, :string
    field :title, :string
    belongs_to :user, TaskTracker.Users.User
    has_many :time_blocks,  TaskTracker.TimeBlocks.TimeBlock

    timestamps()
  end

  @doc false
  def changeset(task, attrs) do
    task
    |> cast(attrs, [:title, :desc, :complete, :user_id])
    |> validate_required([:title, :complete])
  end
end

lib/task_tracker/tasks/tasks.ex
defmodule TaskTracker.Tasks do
  @moduledoc """
  The Tasks context.
  """

  import Ecto.Query, warn: false
  alias TaskTracker.Repo

  alias TaskTracker.Tasks.Task

  @doc """
  Returns the list of tasks.

  ## Examples

      iex> list_tasks()
      [%Task{}, ...]

  """
  def list_tasks do
    Repo.all(Task)
  end

  def list_user_tasks(user_id) do
    query = from t in Task,
             where: t.user_id == ^user_id,
             select: t
    Repo.all(query)
  end

  @doc """
  Gets a single task.

  Raises `Ecto.NoResultsError` if the Task does not exist.

  ## Examples

      iex> get_task!(123)
      %Task{}

      iex> get_task!(456)
      ** (Ecto.NoResultsError)

  """
  #TODO Get rid of this line def get_task!(id), do: Repo.get!(Task, id)

  def get_task!(id) do
    Repo.one! from p in Task,
      where: p.id == ^id,
      preload: [:time_blocks]
  end

  def get_task_by_title(title) do
    Repo.get_by(Task, title: title)
  end

  def user_id_to_name(user_id) do
    if user_id == nil do
      "No User Assigned"
    else
      user = TaskTracker.Users.get_user!(user_id)
      user.name
    end
  end
  @doc """
  Creates a task.

  ## Examples

      iex> create_task(%{field: value})
      {:ok, %Task{}}

      iex> create_task(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_task(attrs \\ %{}) do
    %Task{}
    |> Task.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a task.

  ## Examples

      iex> update_task(task, %{field: new_value})
      {:ok, %Task{}}

      iex> update_task(task, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_task(%Task{} = task, attrs) do
    task
    |> Task.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Task.

  ## Examples

      iex> delete_task(task)
      {:ok, %Task{}}

      iex> delete_task(task)
      {:error, %Ecto.Changeset{}}

  """
  def delete_task(%Task{} = task) do
    Repo.delete(task)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking task changes.

  ## Examples

      iex> change_task(task)
      %Ecto.Changeset{source: %Task{}}

  """
  def change_task(%Task{} = task) do
    Task.changeset(task, %{})
  end
end

lib/task_tracker_web/controllers/task_controller.ex
defmodule TaskTrackerWeb.TaskController do
  use TaskTrackerWeb, :controller

  alias TaskTracker.Tasks
  alias TaskTracker.Tasks.Task
  alias TaskTracker.Users

  def null_user() do
    %{
      id: nil,
      name: "",
    }
  end

  def index(conn, _params) do
    tasks = Tasks.list_tasks()
    render(conn, "index.html", tasks: tasks)
  end

  def new(conn, _params) do
    changeset = Tasks.change_task(%Task{})
    user = conn.assigns.current_user
    if user do
      user_list = [null_user] ++ Users.list_manager_underlings(user.id) ++ [user]
      render(conn, "new.html", task: nil, changeset: changeset,
        list_users: user_list)
    else
      render(conn, "new.html", task: nil, changeset: changeset,
        list_users: [null_user])
    end
  end

  def create(conn, %{"task" => task_params}) do
    case Tasks.create_task(task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task created successfully.")
        |> redirect(to: Routes.task_path(conn, :show, task))

      {:error, %Ecto.Changeset{} = changeset} ->
        user = conn.assigns.current_user
        user_list = [null_user] ++ Users.list_manager_underlings(user.id) ++ [user]
        render(conn, "new.html", changeset: changeset,
          list_users: user_list)
    end
  end

  def show(conn, %{"id" => id}) do
    task = Tasks.get_task!(id)
    time_blocks = TaskTracker.TimeBlocks.list_task_time_blocks(id)
    render(conn, "show.html", task: task, time_blocks: time_blocks)
  end

  def edit(conn, %{"id" => id}) do

    task = Tasks.get_task!(id)
    changeset = Tasks.change_task(task)
    user = conn.assigns.current_user
    user_list = [null_user] ++ Users.list_manager_underlings(user.id) ++ [user]
    render(conn, "edit.html", task: task, changeset: changeset,
      list_users: user_list)
  end

  def update(conn, %{"id" => id, "task" => task_params}) do
    task = Tasks.get_task!(id)

    case Tasks.update_task(task, task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task updated successfully.")
        |> redirect(to: Routes.task_path(conn, :show, task))

      {:error, %Ecto.Changeset{} = changeset} ->
        user = conn.assigns.current_user
        user_list = [null_user] ++ Users.list_manager_underlings(user.id) ++ [user]
        render(conn, "edit.html", task: task, changeset: changeset,
          list_users: user_list)
    end
  end

  def delete(conn, %{"id" => id}) do
    task = Tasks.get_task!(id)
    {:ok, _task} = Tasks.delete_task(task)

    conn
    |> put_flash(:info, "Task deleted successfully.")
    |> redirect(to: Routes.task_path(conn, :index))
  end
end

lib/task_tracker_web/views/task_view.ex
defmodule TaskTrackerWeb.TaskView do
  use TaskTrackerWeb, :view
end

lib/task_tracker_web/templates/task/edit.html.eex
<h1>Edit Task</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.task_path(@conn, :update, @task)) %>

<span><%= link "Back", to: Routes.task_path(@conn, :index), class: "btn btn-secondary" %></span>

lib/task_tracker_web/templates/task/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title %>
    <%= if @changeset.action do %>
      <div class="alert alert-danger">
        <%= error_tag f, :title %>
      </div>
    <% end %>
    <%= text_input f, :title, class: "form-control" %>


    <%= label f, :desc %>
    <%= error_tag f, :desc %>
    <%= textarea f, :desc, class: "form-control" %>
    </br>

    <%= label f, :complete %>
    <%= error_tag f, :complete %>
    <%= checkbox f, :complete %>

    </br>
    <%= label f, :user_id %>
        <%= error_tag f, :user_id %>
    <%= select f, :user_id, Enum.map(@list_users, fn user -> {user.name, user.id} end), class: "form-control" %>


    <div>
      <%= submit "Save", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

lib/task_tracker_web/templates/task/index.html.eex
<h1>Listing Tasks</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Complete</th>
      <th>User</th>
      <th>Date Created</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for task <- @tasks do %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.complete %></td>
      <td><%= TaskTracker.Tasks.user_id_to_name(task.user_id) %></td>
      <td><%= task.inserted_at %></td>

      <td><%= link "Show", to: Routes.task_path(@conn, :show, task), class: "btn btn-info"  %></td>
      <td><%= link "Edit", to: Routes.task_path(@conn, :edit, task), class: "btn btn-light" %></td>
      <td><%= link "Delete", to: Routes.task_path(@conn, :delete, task), class: "btn btn-secondary", method: :delete, data: [confirm: "Are you sure?"] %></td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Task", to: Routes.task_path(@conn, :new), class: "btn btn-primary" %></span>

lib/task_tracker_web/templates/task/new.html.eex
<h1>Create New Task</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.task_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.task_path(@conn, :index), class: "btn btn-secondary" %></span>

lib/task_tracker_web/templates/task/show.html.eex
<h1>Task Information</h1>

<ul>
  <li class="list-group-item">
    <strong>Title:</strong>
    <%= @task.title %>
  </li>

  <li class="list-group-item">
    <strong>Desc:</strong>
    <%= @task.desc %>
  </li>

  <li class="list-group-item">
    <strong>Complete:</strong>
    <%= @task.complete %>
  </li>

  <li class="list-group-item">
    <strong>User:</strong>
    <%= TaskTracker.Tasks.user_id_to_name(@task.user_id) %>
  </li>

  <li class="list-group-item">
    <strong>Date Created:</strong>
    <%= @task.inserted_at %>
  </li>

  <li class="list-group-item">
    <strong>Time Blocks:</strong>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Time Start</th>
          <th>Time End</th>

          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= for time_block <- @time_blocks do %>
          <tr class="time-block-edit">
            <td><input id="time-block-start" type="text" class="form-control" value="<%= time_block.time_start %>"></td>
            <td><input id="time-block-end" type="text" class="form-control" value="<%= time_block.time_end %>"></td>
            <td><button
              data-time-block-id="<%= time_block.id %>"
              data-task-id="<%= @task.id %>"
              data-update-path="<%= Routes.time_block_path(@conn, :update, time_block.id) %>"
              class="btn btn-primary time-update-button">Update Time</button></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </li>
</ul>

<h2>Active Timer</h2>
<ul>
  <li class="list-group-item">
    <div class="row">
      <div class="col">
        <button id="time-start-button" class="btn btn-success">Time Start</button>
      </div>
      <div class="col">
        <p id="time-start-text">Time start</p>
      </div>
    </div>
  </li>
  <li class="list-group-item">
    <div class="row">
      <div class="col">
        <button id="time-end-button"
          data-task-id="<%= @task.id %>"
          class="btn btn-danger">Time End</button>
      </div>
      <div class="col">
        <p id="time-end-text">Time end</p>
      </div>
    </div>
  </li>
</ul>

</br>
</br>
<script>
  window.time_block_path_create = "<%= Routes.time_block_path(@conn, :create) %>"
</script>


<span><%= link "Edit", to: Routes.task_path(@conn, :edit, @task), class: "btn btn-primary" %></span>
<span><%= link "Back", to: Routes.task_path(@conn, :index), class: "btn btn-secondary" %></span>